# Generated by Django 4.2.17 on 2025-01-23 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgbuild', '0004_bgreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgreply',
            old_name='comment_name',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='bgcomment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bgreply',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bgreply',
            name='reply_body',
            field=models.TextField(),
        ),
    ]
