# Generated by Django 4.2.17 on 2025-01-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgbuild', '0005_rename_comment_name_bgreply_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgreply',
            old_name='reply_body',
            new_name='body',
        ),
    ]
