# Generated by Django 4.2.17 on 2025-01-24 13:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgbuild', '0006_rename_reply_body_bgreply_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgbuild',
            name='bgbuild_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
