# Generated by Django 4.2.17 on 2025-01-30 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgbuild', '0007_bgbuild_bgbuild_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgbuild',
            name='favourites',
            field=models.ManyToManyField(related_name='bgbuilds', to=settings.AUTH_USER_MODEL),
        ),
    ]
