# Generated by Django 4.2.17 on 2025-01-30 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgbuild', '0008_bgbuild_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgbuild',
            name='favourites',
            field=models.ManyToManyField(related_name='bgbuild_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
