# Generated by Django 4.2.17 on 2025-02-07 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgbuild', '0009_alter_bgbuild_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgbuild',
            name='classone_level',
        ),
        migrations.AddField(
            model_name='bgbuild',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='bgbuild',
            name='level_split',
            field=models.CharField(choices=[('12', '12'), ('11/1', '11/1'), ('10/2', '10/2'), ('9/3', '9/3'), ('8/4', '8/4'), ('7/5', '7/5'), ('6/6', '6/6'), ('5/7', '5/7'), ('4/8', '4/8'), ('3/9', '3/9'), ('2/10', '2/10'), ('1/11', '1/11')], default='12', max_length=5),
        ),
        migrations.AddField(
            model_name='bgbuild',
            name='main_key_ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='Strength', max_length=15),
        ),
        migrations.AddField(
            model_name='bgbuild',
            name='secondary_key_ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='Dexterity', max_length=15),
        ),
        migrations.AddField(
            model_name='bgbuild',
            name='suggested_skill',
            field=models.CharField(choices=[('arcana', 'Arcana'), ('history', 'History'), ('religion', 'Religion'), ('investigation', 'Investigation'), ('athletics', 'Athletics'), ('nature', 'Nature'), ('acrobatics', 'Acrobatics'), ('sleight of hand', 'Sleight Of Hand'), ('stealth', 'Stealth'), ('animal handling', 'Animal Handling'), ('insight', 'Insight'), ('medicine', 'Medicine'), ('deception', 'Deception'), ('perception', 'Perception'), ('persuasion', 'Persuasion'), ('survival', 'Survival'), ('intimidation', 'Intimidation'), ('performance', 'Performance')], default='Athletics', max_length=15),
        ),
        migrations.AlterField(
            model_name='bgbuild',
            name='bgbuild_title',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='bgbuild',
            name='favourites',
            field=models.ManyToManyField(related_name='bgbuild_favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bgbuild',
            name='slug',
            field=models.SlugField(max_length=28, unique=True),
        ),
    ]
