# Generated by Django 4.2.17 on 2025-02-10 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgbuild', '0010_remove_bgbuild_classone_level_bgbuild_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgbuild',
            name='suggested_skill_secondary',
            field=models.CharField(choices=[('arcana', 'Arcana'), ('history', 'History'), ('religion', 'Religion'), ('investigation', 'Investigation'), ('athletics', 'Athletics'), ('nature', 'Nature'), ('acrobatics', 'Acrobatics'), ('sleight of hand', 'Sleight Of Hand'), ('stealth', 'Stealth'), ('animal handling', 'Animal Handling'), ('insight', 'Insight'), ('medicine', 'Medicine'), ('deception', 'Deception'), ('perception', 'Perception'), ('persuasion', 'Persuasion'), ('survival', 'Survival'), ('intimidation', 'Intimidation'), ('performance', 'Performance')], default='Athletics', max_length=15),
        ),
        migrations.AlterField(
            model_name='bgbuild',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='bgbuild_favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bgbuild',
            name='suggested_skill',
            field=models.CharField(choices=[('arcana', 'Arcana'), ('history', 'History'), ('religion', 'Religion'), ('investigation', 'Investigation'), ('athletics', 'Athletics'), ('nature', 'Nature'), ('acrobatics', 'Acrobatics'), ('sleight of hand', 'Sleight Of Hand'), ('stealth', 'Stealth'), ('animal handling', 'Animal Handling'), ('insight', 'Insight'), ('medicine', 'Medicine'), ('deception', 'Deception'), ('perception', 'Perception'), ('persuasion', 'Persuasion'), ('survival', 'Survival'), ('intimidation', 'Intimidation'), ('performance', 'Performance')], default='Arcana', max_length=15),
        ),
    ]
