# Generated by Django 4.2.17 on 2025-02-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgbuild', '0011_bgbuild_suggested_skill_secondary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='bgreply',
            old_name='body',
            new_name='reply_body',
        ),
    ]
